esphome:
  name: esp121-env
  friendly_name: esp121 датчик CO2

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "X2yRUWRYlExBRPNePyaRxGrRa+WVIxzPh2MDxWZzBZo="

ota:
  - platform: esphome
#    password: "aa2e606e91574a6d44bfd69282bd1dc0"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.10.121
    gateway: 192.168.10.1
    subnet: 255.255.255.0  
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp121-Co2 Fallback Hotspot"
    password: "12345678"

captive_portal:
    
web_server:
  port: 80


  
i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true
  id: bus_a

switch:
  - platform: gpio
    pin:
      number: 2
      inverted: False
    name: "Small LED"
    id: small_led
    
    
esp32_touch:
  setup_mode: false

binary_sensor:
  - platform: esp32_touch
    name: "esp121env Touch Pad"
    pin: GPIO12
    threshold: 1000
    on_press:
      then:
        - switch.turn_on: small_led
    on_release:
      then:
        - switch.turn_off: small_led
    
sensor:
  - platform: wifi_signal
    name: "ESPhome121 env wifi strength"
    update_interval: 30s

  - platform: scd4x
    id: esp121_co2
    co2:
      name: "esp121env CO2"
    temperature:
      name: "esp121env Temp"
      id: esp121_temp
    humidity:
      name: "esp121env Humidity"
      id: esp121_hum
# кнопочка в интерфейсе для калибровки 
button:
  - platform: restart
    name: "N1 ESP121-Env restart"
  - platform: template
    name: "НЕ ТРОГАТЬ! CO2 calibration"
    on_press:
      - logger.log: Calibration Pressed
      - scd4x.perform_forced_calibration:
          value: 430 # outside average Jan 2025
          id: esp121_co2
